name: Lottery Deployment

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: lottery-app/.
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lottery_contract:latest
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:  
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo docker rm -f lottery || true
            sudo docker image rm ${{ secrets.DOCKERHUB_USERNAME }}/lottery_contract:latest || true
            sudo docker run -d -p 4000:4000 --name lottery ${{ secrets.DOCKERHUB_USERNAME }}/lottery_contract:latest || true